# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_Back_updata_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_back_2(object):
    def setupUi(self, Ui_back_2):
        Ui_back_2.setObjectName("Ui_back_2")
        Ui_back_2.resize(1280, 805)
        Ui_back_2.setStyleSheet("background-image:url(:/後端_更新/XD檔/第二版20210727/介面模板/No icon後端更新模型_new.png);")
        self.modol_6s_lab = QtWidgets.QLabel(Ui_back_2)
        self.modol_6s_lab.setGeometry(QtCore.QRect(192, 284, 451, 34))
        self.modol_6s_lab.setStyleSheet("background-image:url(:/後端_登入/XD檔/第二版20210727/元件/密碼方塊.png);")
        self.modol_6s_lab.setText("")
        self.modol_6s_lab.setObjectName("modol_6s_lab")
        self.modol_11s_lab = QtWidgets.QLabel(Ui_back_2)
        self.modol_11s_lab.setGeometry(QtCore.QRect(192, 391, 451, 34))
        self.modol_11s_lab.setStyleSheet("background-image:url(:/後端_登入/XD檔/第二版20210727/元件/密碼方塊.png);")
        self.modol_11s_lab.setText("")
        self.modol_11s_lab.setObjectName("modol_11s_lab")
        self.modol_21s_lab = QtWidgets.QLabel(Ui_back_2)
        self.modol_21s_lab.setGeometry(QtCore.QRect(192, 498, 451, 34))
        self.modol_21s_lab.setStyleSheet("background-image:url(:/後端_登入/XD檔/第二版20210727/元件/密碼方塊.png);")
        self.modol_21s_lab.setText("")
        self.modol_21s_lab.setObjectName("modol_21s_lab")
        self.more_btn_6s = QtWidgets.QPushButton(Ui_back_2)
        self.more_btn_6s.setGeometry(QtCore.QRect(673, 284, 34, 34))
        self.more_btn_6s.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/分析輸入檔案/XD檔/第二版20210727/元件/更多.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}")
        self.more_btn_6s.setText("")
        self.more_btn_6s.setObjectName("more_btn_6s")
        self.more_btn_11s = QtWidgets.QPushButton(Ui_back_2)
        self.more_btn_11s.setGeometry(QtCore.QRect(673, 391, 34, 34))
        self.more_btn_11s.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/分析輸入檔案/XD檔/第二版20210727/元件/更多.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}")
        self.more_btn_11s.setText("")
        self.more_btn_11s.setObjectName("more_btn_11s")
        self.more_btn_21s = QtWidgets.QPushButton(Ui_back_2)
        self.more_btn_21s.setGeometry(QtCore.QRect(673, 498, 34, 34))
        self.more_btn_21s.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/分析輸入檔案/XD檔/第二版20210727/元件/更多.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}")
        self.more_btn_21s.setText("")
        self.more_btn_21s.setObjectName("more_btn_21s")
        self.update_btn = QtWidgets.QPushButton(Ui_back_2)
        self.update_btn.setGeometry(QtCore.QRect(767, 356, 189, 69))
        self.update_btn.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/後端_更新/XD檔/第二版20210727/元件/Update.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/後端_更新/XD檔/第二版20210727/元件/Update_G.png);\n"
"}")
        self.update_btn.setText("")
        self.update_btn.setObjectName("update_btn")
        self.home_b_2 = QtWidgets.QPushButton(Ui_back_2)
        self.home_b_2.setGeometry(QtCore.QRect(1063, 44, 60, 50))
        self.home_b_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home顏色.png);\n"
"}")
        self.home_b_2.setText("")
        self.home_b_2.setObjectName("home_b_2")
        self.exit_b_2 = QtWidgets.QPushButton(Ui_back_2)
        self.exit_b_2.setGeometry(QtCore.QRect(1170, 44, 60, 50))
        self.exit_b_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image:url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image:url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png)\n"
"}")
        self.exit_b_2.setText("")
        self.exit_b_2.setObjectName("exit_b_2")

        self.retranslateUi(Ui_back_2)
        QtCore.QMetaObject.connectSlotsByName(Ui_back_2)

    def retranslateUi(self, Ui_back_2):
        _translate = QtCore.QCoreApplication.translate
        Ui_back_2.setWindowTitle(_translate("Ui_back_2", "Form"))
import XD_2_rc
