# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_DataExtract_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Page2(object):
    def setupUi(self, Ui_Page2):
        Ui_Page2.setObjectName("Ui_Page2")
        Ui_Page2.resize(1280, 800)
        Ui_Page2.setMinimumSize(QtCore.QSize(1280, 800))
        Ui_Page2.setMaximumSize(QtCore.QSize(1280, 800))
        Ui_Page2.setStyleSheet("background-image: url(:/轉換檔案/XD檔/第二版20210727/介面模板/No icon 轉換檔案.png);")
        self.Analysis_btn_2 = QtWidgets.QPushButton(Ui_Page2)
        self.Analysis_btn_2.setGeometry(QtCore.QRect(917, 545, 189, 75))
        self.Analysis_btn_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/首頁/XD檔/第二版20210727/元件/Analysis.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/首頁/XD檔/第二版20210727/元件/Analysis顏色.png);\n"
"}")
        self.Analysis_btn_2.setText("")
        self.Analysis_btn_2.setObjectName("Analysis_btn_2")
        self.home_btn_2 = QtWidgets.QPushButton(Ui_Page2)
        self.home_btn_2.setGeometry(QtCore.QRect(1063, 44, 60, 50))
        self.home_btn_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home顏色.png);\n"
"}")
        self.home_btn_2.setText("")
        self.home_btn_2.setObjectName("home_btn_2")
        self.Exit_btn_2 = QtWidgets.QPushButton(Ui_Page2)
        self.Exit_btn_2.setGeometry(QtCore.QRect(1170, 44, 60, 50))
        self.Exit_btn_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image:url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image:url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png)\n"
"}")
        self.Exit_btn_2.setText("")
        self.Exit_btn_2.setObjectName("Exit_btn_2")

        self.retranslateUi(Ui_Page2)
        QtCore.QMetaObject.connectSlotsByName(Ui_Page2)

    def retranslateUi(self, Ui_Page2):
        _translate = QtCore.QCoreApplication.translate
        Ui_Page2.setWindowTitle(_translate("Ui_Page2", "Form"))
import XD_2_rc
