# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_First_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1280, 800)
        Form.setMinimumSize(QtCore.QSize(1280, 800))
        Form.setMaximumSize(QtCore.QSize(1280, 800))
        Form.setStyleSheet("background-image: url(:/首頁/XD檔/第二版20210727/介面模板/No icon 首頁.png);")
        self.Data_Extract_btn_1 = QtWidgets.QPushButton(Form)
        self.Data_Extract_btn_1.setGeometry(QtCore.QRect(543, 545, 189, 75))
        self.Data_Extract_btn_1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/首頁/XD檔/第二版20210727/元件/Data Extract.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"border-image: url(:/首頁/XD檔/第二版20210727/元件/Data Extract上色.png);\n"
"}")
        self.Data_Extract_btn_1.setText("")
        self.Data_Extract_btn_1.setObjectName("Data_Extract_btn_1")
        self.Analysis_btn = QtWidgets.QPushButton(Form)
        self.Analysis_btn.setGeometry(QtCore.QRect(780, 545, 189, 75))
        self.Analysis_btn.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/首頁/XD檔/第二版20210727/元件/Analysis.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/首頁/XD檔/第二版20210727/元件/Analysis顏色.png);\n"
"}")
        self.Analysis_btn.setText("")
        self.Analysis_btn.setObjectName("Analysis_btn")
        self.Exit_btn_1 = QtWidgets.QPushButton(Form)
        self.Exit_btn_1.setGeometry(QtCore.QRect(1170, 35, 60, 50))
        self.Exit_btn_1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png);\n"
"}")
        self.Exit_btn_1.setText("")
        self.Exit_btn_1.setObjectName("Exit_btn_1")
        self.User_btn = QtWidgets.QPushButton(Form)
        self.User_btn.setGeometry(QtCore.QRect(1071, 35, 60, 50))
        self.User_btn.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/首頁/XD檔/第二版20210727/元件/User.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/首頁/XD檔/第二版20210727/元件/User_G.png);\n"
"}")
        self.User_btn.setText("")
        self.User_btn.setObjectName("User_btn")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
import XD_2_rc
