# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_Back_Success_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Back_3(object):
    def setupUi(self, Ui_Back_3):
        Ui_Back_3.setObjectName("Ui_Back_3")
        Ui_Back_3.resize(1280, 800)
        Ui_Back_3.setStyleSheet("background-image: url(:/更新成功/XD檔/第二版20210727/介面模板/No icon 後端更新模型 – 成功.png);")
        self.Leave_btn = QtWidgets.QPushButton(Ui_Back_3)
        self.Leave_btn.setGeometry(QtCore.QRect(546, 444, 189, 69))
        self.Leave_btn.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/更新成功/XD檔/第二版20210727/元件/Leave.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/更新成功/XD檔/第二版20210727/元件/Leave_G.png);\n"
"}")
        self.Leave_btn.setText("")
        self.Leave_btn.setObjectName("Leave_btn")
        self.home_B_3 = QtWidgets.QPushButton(Ui_Back_3)
        self.home_B_3.setGeometry(QtCore.QRect(1063, 44, 60, 50))
        self.home_B_3.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home顏色.png);\n"
"}")
        self.home_B_3.setText("")
        self.home_B_3.setObjectName("home_B_3")
        self.exit_B_3 = QtWidgets.QPushButton(Ui_Back_3)
        self.exit_B_3.setGeometry(QtCore.QRect(1170, 44, 60, 50))
        self.exit_B_3.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image:url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image:url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png)\n"
"}")
        self.exit_B_3.setText("")
        self.exit_B_3.setObjectName("exit_B_3")

        self.retranslateUi(Ui_Back_3)
        QtCore.QMetaObject.connectSlotsByName(Ui_Back_3)

    def retranslateUi(self, Ui_Back_3):
        _translate = QtCore.QCoreApplication.translate
        Ui_Back_3.setWindowTitle(_translate("Ui_Back_3", "Form"))
import XD_2_rc
