# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_Analysis_1_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_Page3(object):
    def setupUi(self, Ui_Page3):
        Ui_Page3.setObjectName("Ui_Page3")
        Ui_Page3.resize(1280, 800)
        Ui_Page3.setMinimumSize(QtCore.QSize(1280, 800))
        Ui_Page3.setMaximumSize(QtCore.QSize(1280, 800))
        Ui_Page3.setStyleSheet("background-image: url(:/分析輸入檔案/XD檔/第二版20210727/介面模板/No icon 分析 輸入資料.png);")
        self.more_btn_1 = QtWidgets.QPushButton(Ui_Page3)
        self.more_btn_1.setGeometry(QtCore.QRect(671, 320, 34, 34))
        self.more_btn_1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/分析輸入檔案/XD檔/第二版20210727/元件/更多.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"")
        self.more_btn_1.setText("")
        self.more_btn_1.setObjectName("more_btn_1")
        self.more_btn_2 = QtWidgets.QPushButton(Ui_Page3)
        self.more_btn_2.setGeometry(QtCore.QRect(671, 471, 34, 34))
        self.more_btn_2.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/分析輸入檔案/XD檔/第二版20210727/元件/更多.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"")
        self.more_btn_2.setText("")
        self.more_btn_2.setObjectName("more_btn_2")
        self.Analysis_btn_3 = QtWidgets.QPushButton(Ui_Page3)
        self.Analysis_btn_3.setGeometry(QtCore.QRect(767, 365, 189, 69))
        self.Analysis_btn_3.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/首頁/XD檔/第二版20210727/元件/Analysis.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/首頁/XD檔/第二版20210727/元件/Analysis顏色.png);\n"
"}")
        self.Analysis_btn_3.setText("")
        self.Analysis_btn_3.setObjectName("Analysis_btn_3")
        self.home_btn_3 = QtWidgets.QPushButton(Ui_Page3)
        self.home_btn_3.setGeometry(QtCore.QRect(1063, 44, 60, 50))
        self.home_btn_3.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home顏色.png);\n"
"}")
        self.home_btn_3.setText("")
        self.home_btn_3.setObjectName("home_btn_3")
        self.Exit_btn_3 = QtWidgets.QPushButton(Ui_Page3)
        self.Exit_btn_3.setGeometry(QtCore.QRect(1170, 44, 60, 50))
        self.Exit_btn_3.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image:url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image:url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png)\n"
"}")
        self.Exit_btn_3.setText("")
        self.Exit_btn_3.setObjectName("Exit_btn_3")
        self.csv_lab = QtWidgets.QLabel(Ui_Page3)
        self.csv_lab.setGeometry(QtCore.QRect(192, 320, 451, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.csv_lab.setFont(font)
        self.csv_lab.setStyleSheet("background-image: url(:/分析輸入檔案/XD檔/第二版20210727/元件/讀取方塊.png);")
        self.csv_lab.setLineWidth(5)
        self.csv_lab.setText("")
        self.csv_lab.setObjectName("csv_lab")
        self.save_lab = QtWidgets.QLabel(Ui_Page3)
        self.save_lab.setGeometry(QtCore.QRect(192, 471, 451, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.save_lab.setFont(font)
        self.save_lab.setStyleSheet("background-image: url(:/分析輸入檔案/XD檔/第二版20210727/元件/讀取方塊.png);")
        self.save_lab.setText("")
        self.save_lab.setObjectName("save_lab")

        self.retranslateUi(Ui_Page3)
        QtCore.QMetaObject.connectSlotsByName(Ui_Page3)

    def retranslateUi(self, Ui_Page3):
        _translate = QtCore.QCoreApplication.translate
        Ui_Page3.setWindowTitle(_translate("Ui_Page3", "Form"))
import XD_2_rc
