# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_login_failed_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_B_04(object):
    def setupUi(self, Ui_B_04):
        Ui_B_04.setObjectName("Ui_B_04")
        Ui_B_04.resize(1280, 800)
        Ui_B_04.setStyleSheet("background-image: url(:/後端_登入/XD檔/第二版20210727/介面模板/No icon後端登入 失敗.png);")
        self.OK_btn_02 = QtWidgets.QPushButton(Ui_B_04)
        self.OK_btn_02.setGeometry(QtCore.QRect(546, 444, 189, 69))
        self.OK_btn_02.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/顯示圖片/XD檔/第二版20210727/元件/OK.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/顯示圖片/XD檔/第二版20210727/元件/OK_G.png);\n"
"}")
        self.OK_btn_02.setText("")
        self.OK_btn_02.setObjectName("OK_btn_02")
        self.home_btn_02 = QtWidgets.QPushButton(Ui_B_04)
        self.home_btn_02.setGeometry(QtCore.QRect(1063, 44, 60, 50))
        self.home_btn_02.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home顏色.png);\n"
"}")
        self.home_btn_02.setText("")
        self.home_btn_02.setObjectName("home_btn_02")
        self.exit_btn_02 = QtWidgets.QPushButton(Ui_B_04)
        self.exit_btn_02.setGeometry(QtCore.QRect(1170, 44, 60, 50))
        self.exit_btn_02.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image:url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image:url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png)\n"
"}")
        self.exit_btn_02.setText("")
        self.exit_btn_02.setObjectName("exit_btn_02")

        self.retranslateUi(Ui_B_04)
        QtCore.QMetaObject.connectSlotsByName(Ui_B_04)

    def retranslateUi(self, Ui_B_04):
        _translate = QtCore.QCoreApplication.translate
        Ui_B_04.setWindowTitle(_translate("Ui_B_04", "Form"))
import XD_2_rc
