# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_show_picture_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_show_picture(object):
    def setupUi(self, Ui_show_picture):
        Ui_show_picture.setObjectName("Ui_show_picture")
        Ui_show_picture.resize(1280, 800)
        Ui_show_picture.setStyleSheet("background-image: url(:/顯示圖片/XD檔/第二版20210727/介面模板/NO icon顯示圖檔.png);")
        self.OK_btn = QtWidgets.QPushButton(Ui_show_picture)
        self.OK_btn.setGeometry(QtCore.QRect(546, 444, 189, 69))
        self.OK_btn.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/顯示圖片/XD檔/第二版20210727/元件/OK.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/顯示圖片/XD檔/第二版20210727/元件/OK_G.png);\n"
"}")
        self.OK_btn.setText("")
        self.OK_btn.setObjectName("OK_btn")
        self.home_btn_5 = QtWidgets.QPushButton(Ui_show_picture)
        self.home_btn_5.setGeometry(QtCore.QRect(1063, 44, 60, 50))
        self.home_btn_5.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home顏色.png);\n"
"}")
        self.home_btn_5.setText("")
        self.home_btn_5.setObjectName("home_btn_5")
        self.exit_btn_5 = QtWidgets.QPushButton(Ui_show_picture)
        self.exit_btn_5.setGeometry(QtCore.QRect(1170, 44, 60, 50))
        self.exit_btn_5.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image:url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image:url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png)\n"
"}")
        self.exit_btn_5.setText("")
        self.exit_btn_5.setObjectName("exit_btn_5")

        self.retranslateUi(Ui_show_picture)
        QtCore.QMetaObject.connectSlotsByName(Ui_show_picture)

    def retranslateUi(self, Ui_show_picture):
        _translate = QtCore.QCoreApplication.translate
        Ui_show_picture.setWindowTitle(_translate("Ui_show_picture", "Form"))
import XD_2_rc
