# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondUI_Back_login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Ui_back_1(object):
    def setupUi(self, Ui_back_1):
        Ui_back_1.setObjectName("Ui_back_1")
        Ui_back_1.resize(1280, 800)
        Ui_back_1.setStyleSheet("background-image: url(:/後端_登入/XD檔/第二版20210727/介面模板/No icon 後端登入.png);")
        self.login_btn = QtWidgets.QPushButton(Ui_back_1)
        self.login_btn.setGeometry(QtCore.QRect(767, 365, 189, 69))
        self.login_btn.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/後端_登入/XD檔/第二版20210727/元件/Login.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/後端_登入/XD檔/第二版20210727/元件/Login_G.png);\n"
"}")
        self.login_btn.setText("")
        self.login_btn.setObjectName("login_btn")
        self.home_b_1 = QtWidgets.QPushButton(Ui_back_1)
        self.home_b_1.setGeometry(QtCore.QRect(1063, 44, 60, 50))
        self.home_b_1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image: url(:/轉換檔案/XD檔/第二版20210727/元件/home顏色.png);\n"
"}")
        self.home_b_1.setText("")
        self.home_b_1.setObjectName("home_b_1")
        self.exit_b_1 = QtWidgets.QPushButton(Ui_back_1)
        self.exit_b_1.setGeometry(QtCore.QRect(1170, 44, 60, 50))
        self.exit_b_1.setStyleSheet("QPushButton\n"
"{\n"
"background-color:transparent;\n"
"border-image:url(:/首頁/XD檔/第二版20210727/元件/exit.png);\n"
"background:none;\n"
"border:none;\n"
"background-repeat:none;\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    border-image:url(:/首頁/XD檔/第二版20210727/元件/Exit顏色.png)\n"
"}")
        self.exit_b_1.setText("")
        self.exit_b_1.setObjectName("exit_b_1")
        self.account_lab = QtWidgets.QLabel(Ui_back_1)
        self.account_lab.setGeometry(QtCore.QRect(192, 320, 451, 34))
        self.account_lab.setStyleSheet("background-image:url(:/後端_登入/XD檔/第二版20210727/元件/密碼方塊.png);\n"
                                       "border-style:none")
        self.account_lab.setObjectName("account_lab")
        self.password_lab = QtWidgets.QLabel(Ui_back_1)
        self.password_lab.setGeometry(QtCore.QRect(192, 320, 451, 34))
        self.password_lab.setStyleSheet("background-image:url(:/後端_登入/XD檔/第二版20210727/元件/密碼方塊.png);\n"
                                       "border-style:none")
        self.password_lab.setObjectName("password_lab")
        self.account_txt = QtWidgets.QLineEdit(Ui_back_1)
        self.account_txt.setGeometry(QtCore.QRect(192, 320, 451, 34))
        self.account_txt.setStyleSheet("background-image:url(:/後端_登入/XD檔/第二版20210727/元件/密碼方塊.png);\n"
"border-style:none")
        self.account_txt.setObjectName("account_txt")
        self.password_txt = QtWidgets.QLineEdit(Ui_back_1)
        self.password_txt.setGeometry(QtCore.QRect(192, 471, 451, 34))
        self.password_txt.setStyleSheet("background-image:url(:/後端_登入/XD檔/第二版20210727/元件/密碼方塊.png);\n"
"border-style:none")
        self.password_txt.setObjectName("password_txt")

        self.retranslateUi(Ui_back_1)
        QtCore.QMetaObject.connectSlotsByName(Ui_back_1)

    def retranslateUi(self, Ui_back_1):
        _translate = QtCore.QCoreApplication.translate
        Ui_back_1.setWindowTitle(_translate("Ui_back_1", "Form"))
import XD_2_rc
